version: '3'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=root
  
  mongo-express:
    image: mongo-express
    depends_on: 
      - mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root

  api:
    build: .
    container_name: api_projet
    ports:
      - 9000:9000
    environment:
      - FLASK_APP=${FLASK_APP}
      - DB_STRING=${DB_STRING}

