from flask import Flask, render_template, request, redirect, url_for, Blueprint  
from src.db import *
# from db import *

init_app_routes = Blueprint('init_routes', __name__)

#   page d'accueil du site permettant de répondre aux questionnaire
@init_app_routes.route("/")
@init_app_routes.route("/accueil", methods=['GET', 'POST'])
def accueil():
    if request.method == 'POST':
      question1 = request.form.get('question1')
      question2 = request.form.get('question2')
      question3 = request.form.get('question3')
      question4 = request.form.get('question4')
      question5 = request.form.get('question5')
      question6 = request.form.get('question6')
      question7 = request.form.get('question7')
      question8 = request.form.get('question8')
      question9 = request.form.get('question9')
      question10 = request.form.get('question10')
      question11 = request.form.get('question11')
      question12 = request.form.get('question12')
      question13 = request.form.get('question13')
      question14 = request.form.get('question14')
      question15 = request.form.get('question15')
      question16 = request.form.get('question16')
      question17 = request.form.get('question17')
      question18 = request.form.get('question18')
      question19 = request.form.get('question19')
      question20 = request.form.get('question20')
      question21 = request.form.get('question21')
      question22 = request.form.get('question22')
      question23 = request.form.get('question23')
      question24 = request.form.get('question24')
      question25 = request.form.get('question25')
      question26 = request.form.get('question26')
      question27 = request.form.get('question27')
      question28 = request.form.get('question28')
      question29 = request.form.get('question29')
      question30 = request.form.get('question30')
      question31 = request.form.get('question31')
      question32 = request.form.get('question32')
      question33 = request.form.get('question33')
      question34 = request.form.get('question34')
      question35 = request.form.get('question35')
      question36 = request.form.get('question36')
      question37 = request.form.get('question37')
      question38 = request.form.get('question38')
      question39 = request.form.get('question39')
      question40 = request.form.get('question40')
      question41 = request.form.get('question41')
      question42 = request.form.get('question42')
      question43 = request.form.get('question43')
      question44 = request.form.get('question44')
      question45 = request.form.get('question45')
      question46 = request.form.get('question46')
      question47 = request.form.get('question47')
      question48 = request.form.get('question48')
      question49 = request.form.get('question49')
      question50 = request.form.get('question50')
      question51 = request.form.get('question51')
      question52 = request.form.get('question52')
      question53 = request.form.get('question53')
      question54 = request.form.get('question54')
      question55 = request.form.get('question55')
      question56 = request.form.get('question56')
      question57 = request.form.get('question57')
      question58 = request.form.get('question58')
      question59 = request.form.get('question59')
      question60 = request.form.get('question60')
      question61 = request.form.get('question61')
      question62 = request.form.get('question62')
      question63 = request.form.get('question63')
      question64 = request.form.get('question64')
      question65 = request.form.get('question65')
      question66 = request.form.get('question66')
      question67 = request.form.get('question67')
      question68 = request.form.get('question68')
      question69 = request.form.get('question69')
      question70 = request.form.get('question70')
      question71 = request.form.get('question71')
      question72 = request.form.get('question72')
      question73 = request.form.get('question73')
      question74 = request.form.get('question74')
      send_questionnaire1(question1,question2,question3,question4,question5,question6,question7,question8,question9,question10,question11,question12,question13,question14,question15,question16,question17,question18,question19,question20,question21,question22,question23,question24,question25,question26,question27,question28)
      send_questionnaire2(question29,question30,question31,question32,question33,question34,question35,question36,question37,question38,question39,question40)
      send_questionnaire3(question41,question42,question43,question44,question45,question46,question47,question48,question49,question50)
      send_questionnaire4(question51,question52,question53,question54,question55,question56,question57,question58,question59,question60,question61,question62)
      send_questionnaire5(question63,question64,question65,question66,question67,question68,question69,question70,question71,question72,question73,question74)
    return render_template('accueil.html')


#   page de connexion du site
@init_app_routes.route("/index", methods=['GET', 'POST'])
def index():
      if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        utilisateur = get_user(email, password)
        print(utilisateur)
        if utilisateur != "{_id: ObjectID()}":
          return redirect(url_for('init_routes.accueil'))
      return render_template('index.html')

#   page d'inscription du site
@init_app_routes.route("/inscription", methods=['GET', 'POST'])
def inscription():
      if request.method == 'POST':
         prenom = request.form.get('prenom')
         nom = request.form.get('nom')
         email = request.form.get('email')
         password = request.form.get('password')
         confpassword = request.get.form('password')
         if(confpassword == password):
          save_user(email,password,nom,prenom)   
          return redirect(url_for('init_routes.index'))
         else:
          return redirect(url_for('init_routes.inscription'))  
      return render_template('inscription.html')
